version: '3.8'

services:
  # Main API service
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=false
      - LOG_LEVEL=INFO
      - MODEL_PATH=/app/models/best_model.h5
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Training service (optional)
  training:
    build: .
    command: python train.py --data_dir /app/data/train --epochs 50 --batch_size 32
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    profiles:
      - training
    restart: "no"

  # Development service with hot reload
  dev:
    build: .
    command: python app.py
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=true
      - API_RELOAD=true
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    profiles:
      - dev
    restart: unless-stopped

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    profiles:
      - production
    restart: unless-stopped

volumes:
  models:
  data:
  logs:
